/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbView: typeof import('./components/BreadcrumbView.vue')['default']
    CategoryNav: typeof import('./components/CategoryNav.vue')['default']
    CategorySelect: typeof import('./components/CategorySelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElResult: typeof import('element-plus/es')['ElResult']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    OrderCountdown: typeof import('./components/OrderCountdown.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./components/StatusTag.vue')['default']
  }
}
